version: "3.2"

services:
  wordpress:
    build: .
    restart: always
    container_name: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - plugins:/var/www/html/wp-content/plugins
      - ./src:/var/www/html/wp-content/plugins/nullify-empty-fields-for-acf

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  plugins:
  db:
